// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/performance.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_performance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{0}
}

type InternScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternScore) Reset() {
	*x = InternScore{}
	mi := &file_proto_performance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternScore) ProtoMessage() {}

func (x *InternScore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternScore.ProtoReflect.Descriptor instead.
func (*InternScore) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{1}
}

func (x *InternScore) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InternScore) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InternScore) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type PerformanceMetricsResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TopPerformers          []*InternScore         `protobuf:"bytes,1,rep,name=top_performers,json=topPerformers,proto3" json:"top_performers,omitempty"`
	LowestPerformers       []*InternScore         `protobuf:"bytes,2,rep,name=lowest_performers,json=lowestPerformers,proto3" json:"lowest_performers,omitempty"`
	AverageEvaluationScore float32                `protobuf:"fixed32,3,opt,name=average_evaluation_score,json=averageEvaluationScore,proto3" json:"average_evaluation_score,omitempty"`
	DomainWisePerformance  map[string]float32     `protobuf:"bytes,4,rep,name=domain_wise_performance,json=domainWisePerformance,proto3" json:"domain_wise_performance,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	CollegeWisePerformance map[string]float32     `protobuf:"bytes,5,rep,name=college_wise_performance,json=collegeWisePerformance,proto3" json:"college_wise_performance,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PerformanceMetricsResponse) Reset() {
	*x = PerformanceMetricsResponse{}
	mi := &file_proto_performance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformanceMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceMetricsResponse) ProtoMessage() {}

func (x *PerformanceMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceMetricsResponse.ProtoReflect.Descriptor instead.
func (*PerformanceMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{2}
}

func (x *PerformanceMetricsResponse) GetTopPerformers() []*InternScore {
	if x != nil {
		return x.TopPerformers
	}
	return nil
}

func (x *PerformanceMetricsResponse) GetLowestPerformers() []*InternScore {
	if x != nil {
		return x.LowestPerformers
	}
	return nil
}

func (x *PerformanceMetricsResponse) GetAverageEvaluationScore() float32 {
	if x != nil {
		return x.AverageEvaluationScore
	}
	return 0
}

func (x *PerformanceMetricsResponse) GetDomainWisePerformance() map[string]float32 {
	if x != nil {
		return x.DomainWisePerformance
	}
	return nil
}

func (x *PerformanceMetricsResponse) GetCollegeWisePerformance() map[string]float32 {
	if x != nil {
		return x.CollegeWisePerformance
	}
	return nil
}

type InternHealthResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ActiveInterns         int32                  `protobuf:"varint,1,opt,name=active_interns,json=activeInterns,proto3" json:"active_interns,omitempty"`
	CompletedInternships  int32                  `protobuf:"varint,2,opt,name=completed_internships,json=completedInternships,proto3" json:"completed_internships,omitempty"`
	InactiveInterns       int32                  `protobuf:"varint,3,opt,name=inactive_interns,json=inactiveInterns,proto3" json:"inactive_interns,omitempty"`
	TopColleges           map[string]int32       `protobuf:"bytes,4,rep,name=top_colleges,json=topColleges,proto3" json:"top_colleges,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FastestGrowingDomains map[string]int32       `protobuf:"bytes,5,rep,name=fastest_growing_domains,json=fastestGrowingDomains,proto3" json:"fastest_growing_domains,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InternHealthResponse) Reset() {
	*x = InternHealthResponse{}
	mi := &file_proto_performance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternHealthResponse) ProtoMessage() {}

func (x *InternHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternHealthResponse.ProtoReflect.Descriptor instead.
func (*InternHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{3}
}

func (x *InternHealthResponse) GetActiveInterns() int32 {
	if x != nil {
		return x.ActiveInterns
	}
	return 0
}

func (x *InternHealthResponse) GetCompletedInternships() int32 {
	if x != nil {
		return x.CompletedInternships
	}
	return 0
}

func (x *InternHealthResponse) GetInactiveInterns() int32 {
	if x != nil {
		return x.InactiveInterns
	}
	return 0
}

func (x *InternHealthResponse) GetTopColleges() map[string]int32 {
	if x != nil {
		return x.TopColleges
	}
	return nil
}

func (x *InternHealthResponse) GetFastestGrowingDomains() map[string]int32 {
	if x != nil {
		return x.FastestGrowingDomains
	}
	return nil
}

type InternTaskStat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InternId       string                 `protobuf:"bytes,1,opt,name=intern_id,json=internId,proto3" json:"intern_id,omitempty"`
	InternName     string                 `protobuf:"bytes,2,opt,name=intern_name,json=internName,proto3" json:"intern_name,omitempty"`
	CompletionRate float32                `protobuf:"fixed32,3,opt,name=completion_rate,json=completionRate,proto3" json:"completion_rate,omitempty"`
	Count          int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InternTaskStat) Reset() {
	*x = InternTaskStat{}
	mi := &file_proto_performance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternTaskStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternTaskStat) ProtoMessage() {}

func (x *InternTaskStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternTaskStat.ProtoReflect.Descriptor instead.
func (*InternTaskStat) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{4}
}

func (x *InternTaskStat) GetInternId() string {
	if x != nil {
		return x.InternId
	}
	return ""
}

func (x *InternTaskStat) GetInternName() string {
	if x != nil {
		return x.InternName
	}
	return ""
}

func (x *InternTaskStat) GetCompletionRate() float32 {
	if x != nil {
		return x.CompletionRate
	}
	return 0
}

func (x *InternTaskStat) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TaskTitleStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskTitleStat) Reset() {
	*x = TaskTitleStat{}
	mi := &file_proto_performance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskTitleStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskTitleStat) ProtoMessage() {}

func (x *TaskTitleStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskTitleStat.ProtoReflect.Descriptor instead.
func (*TaskTitleStat) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{5}
}

func (x *TaskTitleStat) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TaskTitleStat) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DomainApprovalStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	ApprovalRate  float32                `protobuf:"fixed32,2,opt,name=approval_rate,json=approvalRate,proto3" json:"approval_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainApprovalStat) Reset() {
	*x = DomainApprovalStat{}
	mi := &file_proto_performance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainApprovalStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainApprovalStat) ProtoMessage() {}

func (x *DomainApprovalStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainApprovalStat.ProtoReflect.Descriptor instead.
func (*DomainApprovalStat) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{6}
}

func (x *DomainApprovalStat) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *DomainApprovalStat) GetApprovalRate() float32 {
	if x != nil {
		return x.ApprovalRate
	}
	return 0
}

type MentorSpeedStat struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MentorName         string                 `protobuf:"bytes,1,opt,name=mentor_name,json=mentorName,proto3" json:"mentor_name,omitempty"`
	AvgCompletionHours float32                `protobuf:"fixed32,2,opt,name=avg_completion_hours,json=avgCompletionHours,proto3" json:"avg_completion_hours,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MentorSpeedStat) Reset() {
	*x = MentorSpeedStat{}
	mi := &file_proto_performance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentorSpeedStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentorSpeedStat) ProtoMessage() {}

func (x *MentorSpeedStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentorSpeedStat.ProtoReflect.Descriptor instead.
func (*MentorSpeedStat) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{7}
}

func (x *MentorSpeedStat) GetMentorName() string {
	if x != nil {
		return x.MentorName
	}
	return ""
}

func (x *MentorSpeedStat) GetAvgCompletionHours() float32 {
	if x != nil {
		return x.AvgCompletionHours
	}
	return 0
}

type PendingTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DaysPending   int32                  `protobuf:"varint,3,opt,name=days_pending,json=daysPending,proto3" json:"days_pending,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingTask) Reset() {
	*x = PendingTask{}
	mi := &file_proto_performance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingTask) ProtoMessage() {}

func (x *PendingTask) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingTask.ProtoReflect.Descriptor instead.
func (*PendingTask) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{8}
}

func (x *PendingTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PendingTask) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PendingTask) GetDaysPending() int32 {
	if x != nil {
		return x.DaysPending
	}
	return 0
}

type TaskTimeCorrelation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	AvgMinutes    float32                `protobuf:"fixed32,2,opt,name=avg_minutes,json=avgMinutes,proto3" json:"avg_minutes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskTimeCorrelation) Reset() {
	*x = TaskTimeCorrelation{}
	mi := &file_proto_performance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskTimeCorrelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskTimeCorrelation) ProtoMessage() {}

func (x *TaskTimeCorrelation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskTimeCorrelation.ProtoReflect.Descriptor instead.
func (*TaskTimeCorrelation) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{9}
}

func (x *TaskTimeCorrelation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskTimeCorrelation) GetAvgMinutes() float32 {
	if x != nil {
		return x.AvgMinutes
	}
	return 0
}

type TaskAnalyticsResponse struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	HighestCompletionRate          []*InternTaskStat      `protobuf:"bytes,1,rep,name=highest_completion_rate,json=highestCompletionRate,proto3" json:"highest_completion_rate,omitempty"`
	MostLateTasks                  []*InternTaskStat      `protobuf:"bytes,2,rep,name=most_late_tasks,json=mostLateTasks,proto3" json:"most_late_tasks,omitempty"`
	FrequentlyRejectedTasks        []*TaskTitleStat       `protobuf:"bytes,3,rep,name=frequently_rejected_tasks,json=frequentlyRejectedTasks,proto3" json:"frequently_rejected_tasks,omitempty"`
	IncompleteTasksPercentage      float32                `protobuf:"fixed32,4,opt,name=incomplete_tasks_percentage,json=incompleteTasksPercentage,proto3" json:"incomplete_tasks_percentage,omitempty"`
	DomainApprovalRates            []*DomainApprovalStat  `protobuf:"bytes,5,rep,name=domain_approval_rates,json=domainApprovalRates,proto3" json:"domain_approval_rates,omitempty"`
	FastestMentorInterns           []*MentorSpeedStat     `protobuf:"bytes,6,rep,name=fastest_mentor_interns,json=fastestMentorInterns,proto3" json:"fastest_mentor_interns,omitempty"`
	DecreasedCompletionRate        []*InternTaskStat      `protobuf:"bytes,7,rep,name=decreased_completion_rate,json=decreasedCompletionRate,proto3" json:"decreased_completion_rate,omitempty"`
	TopRejectionReasons            []string               `protobuf:"bytes,8,rep,name=top_rejection_reasons,json=topRejectionReasons,proto3" json:"top_rejection_reasons,omitempty"`
	ConsistentEarlySubmitters      []*InternTaskStat      `protobuf:"bytes,9,rep,name=consistent_early_submitters,json=consistentEarlySubmitters,proto3" json:"consistent_early_submitters,omitempty"`
	LongPendingTasks               []*PendingTask         `protobuf:"bytes,10,rep,name=long_pending_tasks,json=longPendingTasks,proto3" json:"long_pending_tasks,omitempty"`
	TasksWithoutEvidencePercentage float32                `protobuf:"fixed32,11,opt,name=tasks_without_evidence_percentage,json=tasksWithoutEvidencePercentage,proto3" json:"tasks_without_evidence_percentage,omitempty"`
	TasksWithMostBlockers          []*TaskTitleStat       `protobuf:"bytes,12,rep,name=tasks_with_most_blockers,json=tasksWithMostBlockers,proto3" json:"tasks_with_most_blockers,omitempty"`
	TimeVsApprovalCorrelation      []*TaskTimeCorrelation `protobuf:"bytes,13,rep,name=time_vs_approval_correlation,json=timeVsApprovalCorrelation,proto3" json:"time_vs_approval_correlation,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *TaskAnalyticsResponse) Reset() {
	*x = TaskAnalyticsResponse{}
	mi := &file_proto_performance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAnalyticsResponse) ProtoMessage() {}

func (x *TaskAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*TaskAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{10}
}

func (x *TaskAnalyticsResponse) GetHighestCompletionRate() []*InternTaskStat {
	if x != nil {
		return x.HighestCompletionRate
	}
	return nil
}

func (x *TaskAnalyticsResponse) GetMostLateTasks() []*InternTaskStat {
	if x != nil {
		return x.MostLateTasks
	}
	return nil
}

func (x *TaskAnalyticsResponse) GetFrequentlyRejectedTasks() []*TaskTitleStat {
	if x != nil {
		return x.FrequentlyRejectedTasks
	}
	return nil
}

func (x *TaskAnalyticsResponse) GetIncompleteTasksPercentage() float32 {
	if x != nil {
		return x.IncompleteTasksPercentage
	}
	return 0
}

func (x *TaskAnalyticsResponse) GetDomainApprovalRates() []*DomainApprovalStat {
	if x != nil {
		return x.DomainApprovalRates
	}
	return nil
}

func (x *TaskAnalyticsResponse) GetFastestMentorInterns() []*MentorSpeedStat {
	if x != nil {
		return x.FastestMentorInterns
	}
	return nil
}

func (x *TaskAnalyticsResponse) GetDecreasedCompletionRate() []*InternTaskStat {
	if x != nil {
		return x.DecreasedCompletionRate
	}
	return nil
}

func (x *TaskAnalyticsResponse) GetTopRejectionReasons() []string {
	if x != nil {
		return x.TopRejectionReasons
	}
	return nil
}

func (x *TaskAnalyticsResponse) GetConsistentEarlySubmitters() []*InternTaskStat {
	if x != nil {
		return x.ConsistentEarlySubmitters
	}
	return nil
}

func (x *TaskAnalyticsResponse) GetLongPendingTasks() []*PendingTask {
	if x != nil {
		return x.LongPendingTasks
	}
	return nil
}

func (x *TaskAnalyticsResponse) GetTasksWithoutEvidencePercentage() float32 {
	if x != nil {
		return x.TasksWithoutEvidencePercentage
	}
	return 0
}

func (x *TaskAnalyticsResponse) GetTasksWithMostBlockers() []*TaskTitleStat {
	if x != nil {
		return x.TasksWithMostBlockers
	}
	return nil
}

func (x *TaskAnalyticsResponse) GetTimeVsApprovalCorrelation() []*TaskTimeCorrelation {
	if x != nil {
		return x.TimeVsApprovalCorrelation
	}
	return nil
}

type MentorStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MentorName    string                 `protobuf:"bytes,1,opt,name=mentor_name,json=mentorName,proto3" json:"mentor_name,omitempty"`
	StatValue     float32                `protobuf:"fixed32,2,opt,name=stat_value,json=statValue,proto3" json:"stat_value,omitempty"`
	ExtraInfo     string                 `protobuf:"bytes,3,opt,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MentorStat) Reset() {
	*x = MentorStat{}
	mi := &file_proto_performance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentorStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentorStat) ProtoMessage() {}

func (x *MentorStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentorStat.ProtoReflect.Descriptor instead.
func (*MentorStat) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{11}
}

func (x *MentorStat) GetMentorName() string {
	if x != nil {
		return x.MentorName
	}
	return ""
}

func (x *MentorStat) GetStatValue() float32 {
	if x != nil {
		return x.StatValue
	}
	return 0
}

func (x *MentorStat) GetExtraInfo() string {
	if x != nil {
		return x.ExtraInfo
	}
	return ""
}

type DomainMentorStat struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DomainName         string                 `protobuf:"bytes,1,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
	MentorName         string                 `protobuf:"bytes,2,opt,name=mentor_name,json=mentorName,proto3" json:"mentor_name,omitempty"`
	EffectivenessScore float32                `protobuf:"fixed32,3,opt,name=effectiveness_score,json=effectivenessScore,proto3" json:"effectiveness_score,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DomainMentorStat) Reset() {
	*x = DomainMentorStat{}
	mi := &file_proto_performance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainMentorStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainMentorStat) ProtoMessage() {}

func (x *DomainMentorStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainMentorStat.ProtoReflect.Descriptor instead.
func (*DomainMentorStat) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{12}
}

func (x *DomainMentorStat) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

func (x *DomainMentorStat) GetMentorName() string {
	if x != nil {
		return x.MentorName
	}
	return ""
}

func (x *DomainMentorStat) GetEffectivenessScore() float32 {
	if x != nil {
		return x.EffectivenessScore
	}
	return 0
}

type MentorAnalyticsResponse struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	LargestInternCount         []*MentorStat          `protobuf:"bytes,1,rep,name=largest_intern_count,json=largestInternCount,proto3" json:"largest_intern_count,omitempty"`
	HighestAvgEvaluation       []*MentorStat          `protobuf:"bytes,2,rep,name=highest_avg_evaluation,json=highestAvgEvaluation,proto3" json:"highest_avg_evaluation,omitempty"`
	LowestAttendanceRate       []*MentorStat          `protobuf:"bytes,3,rep,name=lowest_attendance_rate,json=lowestAttendanceRate,proto3" json:"lowest_attendance_rate,omitempty"`
	HighestTaskApproval        []*MentorStat          `protobuf:"bytes,4,rep,name=highest_task_approval,json=highestTaskApproval,proto3" json:"highest_task_approval,omitempty"`
	HighestRetentionRate       []*MentorStat          `protobuf:"bytes,5,rep,name=highest_retention_rate,json=highestRetentionRate,proto3" json:"highest_retention_rate,omitempty"`
	ConsistentlyMissDeadlines  []*MentorStat          `protobuf:"bytes,6,rep,name=consistently_miss_deadlines,json=consistentlyMissDeadlines,proto3" json:"consistently_miss_deadlines,omitempty"`
	BalancedWorkload           []*MentorStat          `protobuf:"bytes,7,rep,name=balanced_workload,json=balancedWorkload,proto3" json:"balanced_workload,omitempty"`
	NeedsIntervention          []*MentorStat          `protobuf:"bytes,8,rep,name=needs_intervention,json=needsIntervention,proto3" json:"needs_intervention,omitempty"`
	EffectivenessAcrossDomains []*DomainMentorStat    `protobuf:"bytes,9,rep,name=effectiveness_across_domains,json=effectivenessAcrossDomains,proto3" json:"effectiveness_across_domains,omitempty"`
	LaggingAssessments         []*MentorStat          `protobuf:"bytes,10,rep,name=lagging_assessments,json=laggingAssessments,proto3" json:"lagging_assessments,omitempty"`
	NegativeEmptyFeedback      []*MentorStat          `protobuf:"bytes,11,rep,name=negative_empty_feedback,json=negativeEmptyFeedback,proto3" json:"negative_empty_feedback,omitempty"`
	DisputedEvidenceFlags      []*MentorStat          `protobuf:"bytes,12,rep,name=disputed_evidence_flags,json=disputedEvidenceFlags,proto3" json:"disputed_evidence_flags,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *MentorAnalyticsResponse) Reset() {
	*x = MentorAnalyticsResponse{}
	mi := &file_proto_performance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MentorAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MentorAnalyticsResponse) ProtoMessage() {}

func (x *MentorAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MentorAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*MentorAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{13}
}

func (x *MentorAnalyticsResponse) GetLargestInternCount() []*MentorStat {
	if x != nil {
		return x.LargestInternCount
	}
	return nil
}

func (x *MentorAnalyticsResponse) GetHighestAvgEvaluation() []*MentorStat {
	if x != nil {
		return x.HighestAvgEvaluation
	}
	return nil
}

func (x *MentorAnalyticsResponse) GetLowestAttendanceRate() []*MentorStat {
	if x != nil {
		return x.LowestAttendanceRate
	}
	return nil
}

func (x *MentorAnalyticsResponse) GetHighestTaskApproval() []*MentorStat {
	if x != nil {
		return x.HighestTaskApproval
	}
	return nil
}

func (x *MentorAnalyticsResponse) GetHighestRetentionRate() []*MentorStat {
	if x != nil {
		return x.HighestRetentionRate
	}
	return nil
}

func (x *MentorAnalyticsResponse) GetConsistentlyMissDeadlines() []*MentorStat {
	if x != nil {
		return x.ConsistentlyMissDeadlines
	}
	return nil
}

func (x *MentorAnalyticsResponse) GetBalancedWorkload() []*MentorStat {
	if x != nil {
		return x.BalancedWorkload
	}
	return nil
}

func (x *MentorAnalyticsResponse) GetNeedsIntervention() []*MentorStat {
	if x != nil {
		return x.NeedsIntervention
	}
	return nil
}

func (x *MentorAnalyticsResponse) GetEffectivenessAcrossDomains() []*DomainMentorStat {
	if x != nil {
		return x.EffectivenessAcrossDomains
	}
	return nil
}

func (x *MentorAnalyticsResponse) GetLaggingAssessments() []*MentorStat {
	if x != nil {
		return x.LaggingAssessments
	}
	return nil
}

func (x *MentorAnalyticsResponse) GetNegativeEmptyFeedback() []*MentorStat {
	if x != nil {
		return x.NegativeEmptyFeedback
	}
	return nil
}

func (x *MentorAnalyticsResponse) GetDisputedEvidenceFlags() []*MentorStat {
	if x != nil {
		return x.DisputedEvidenceFlags
	}
	return nil
}

type EngagementStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InternId      string                 `protobuf:"bytes,1,opt,name=intern_id,json=internId,proto3" json:"intern_id,omitempty"`
	InternName    string                 `protobuf:"bytes,2,opt,name=intern_name,json=internName,proto3" json:"intern_name,omitempty"`
	StatValue     float32                `protobuf:"fixed32,3,opt,name=stat_value,json=statValue,proto3" json:"stat_value,omitempty"`
	ExtraInfo     string                 `protobuf:"bytes,4,opt,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngagementStat) Reset() {
	*x = EngagementStat{}
	mi := &file_proto_performance_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngagementStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngagementStat) ProtoMessage() {}

func (x *EngagementStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngagementStat.ProtoReflect.Descriptor instead.
func (*EngagementStat) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{14}
}

func (x *EngagementStat) GetInternId() string {
	if x != nil {
		return x.InternId
	}
	return ""
}

func (x *EngagementStat) GetInternName() string {
	if x != nil {
		return x.InternName
	}
	return ""
}

func (x *EngagementStat) GetStatValue() float32 {
	if x != nil {
		return x.StatValue
	}
	return 0
}

func (x *EngagementStat) GetExtraInfo() string {
	if x != nil {
		return x.ExtraInfo
	}
	return ""
}

type CollegeEngagementStat struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CollegeName        string                 `protobuf:"bytes,1,opt,name=college_name,json=collegeName,proto3" json:"college_name,omitempty"`
	AvgEngagementScore float32                `protobuf:"fixed32,2,opt,name=avg_engagement_score,json=avgEngagementScore,proto3" json:"avg_engagement_score,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CollegeEngagementStat) Reset() {
	*x = CollegeEngagementStat{}
	mi := &file_proto_performance_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollegeEngagementStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollegeEngagementStat) ProtoMessage() {}

func (x *CollegeEngagementStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollegeEngagementStat.ProtoReflect.Descriptor instead.
func (*CollegeEngagementStat) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{15}
}

func (x *CollegeEngagementStat) GetCollegeName() string {
	if x != nil {
		return x.CollegeName
	}
	return ""
}

func (x *CollegeEngagementStat) GetAvgEngagementScore() float32 {
	if x != nil {
		return x.AvgEngagementScore
	}
	return 0
}

type EngagementAnalyticsResponse struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	NoRecentAttendance     []*EngagementStat        `protobuf:"bytes,1,rep,name=no_recent_attendance,json=noRecentAttendance,proto3" json:"no_recent_attendance,omitempty"`
	DecliningParticipation []*EngagementStat        `protobuf:"bytes,2,rep,name=declining_participation,json=decliningParticipation,proto3" json:"declining_participation,omitempty"`
	StoppedDailyReports    []*EngagementStat        `protobuf:"bytes,3,rep,name=stopped_daily_reports,json=stoppedDailyReports,proto3" json:"stopped_daily_reports,omitempty"`
	LostActiveStreaks      []*EngagementStat        `protobuf:"bytes,4,rep,name=lost_active_streaks,json=lostActiveStreaks,proto3" json:"lost_active_streaks,omitempty"`
	MostEngagedInterns     []*EngagementStat        `protobuf:"bytes,5,rep,name=most_engaged_interns,json=mostEngagedInterns,proto3" json:"most_engaged_interns,omitempty"`
	AtRiskInterns          []*EngagementStat        `protobuf:"bytes,6,rep,name=at_risk_interns,json=atRiskInterns,proto3" json:"at_risk_interns,omitempty"`
	SuddenActivityDrops    []*EngagementStat        `protobuf:"bytes,7,rep,name=sudden_activity_drops,json=suddenActivityDrops,proto3" json:"sudden_activity_drops,omitempty"`
	TopEngagedColleges     []*CollegeEngagementStat `protobuf:"bytes,8,rep,name=top_engaged_colleges,json=topEngagedColleges,proto3" json:"top_engaged_colleges,omitempty"`
	StuckOrBlocked         []*EngagementStat        `protobuf:"bytes,9,rep,name=stuck_or_blocked,json=stuckOrBlocked,proto3" json:"stuck_or_blocked,omitempty"`
	MissingOrPartialSignal []*EngagementStat        `protobuf:"bytes,10,rep,name=missing_or_partial_signal,json=missingOrPartialSignal,proto3" json:"missing_or_partial_signal,omitempty"`
	HighMessagesLowTasks   []*EngagementStat        `protobuf:"bytes,11,rep,name=high_messages_low_tasks,json=highMessagesLowTasks,proto3" json:"high_messages_low_tasks,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EngagementAnalyticsResponse) Reset() {
	*x = EngagementAnalyticsResponse{}
	mi := &file_proto_performance_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngagementAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngagementAnalyticsResponse) ProtoMessage() {}

func (x *EngagementAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngagementAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*EngagementAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{16}
}

func (x *EngagementAnalyticsResponse) GetNoRecentAttendance() []*EngagementStat {
	if x != nil {
		return x.NoRecentAttendance
	}
	return nil
}

func (x *EngagementAnalyticsResponse) GetDecliningParticipation() []*EngagementStat {
	if x != nil {
		return x.DecliningParticipation
	}
	return nil
}

func (x *EngagementAnalyticsResponse) GetStoppedDailyReports() []*EngagementStat {
	if x != nil {
		return x.StoppedDailyReports
	}
	return nil
}

func (x *EngagementAnalyticsResponse) GetLostActiveStreaks() []*EngagementStat {
	if x != nil {
		return x.LostActiveStreaks
	}
	return nil
}

func (x *EngagementAnalyticsResponse) GetMostEngagedInterns() []*EngagementStat {
	if x != nil {
		return x.MostEngagedInterns
	}
	return nil
}

func (x *EngagementAnalyticsResponse) GetAtRiskInterns() []*EngagementStat {
	if x != nil {
		return x.AtRiskInterns
	}
	return nil
}

func (x *EngagementAnalyticsResponse) GetSuddenActivityDrops() []*EngagementStat {
	if x != nil {
		return x.SuddenActivityDrops
	}
	return nil
}

func (x *EngagementAnalyticsResponse) GetTopEngagedColleges() []*CollegeEngagementStat {
	if x != nil {
		return x.TopEngagedColleges
	}
	return nil
}

func (x *EngagementAnalyticsResponse) GetStuckOrBlocked() []*EngagementStat {
	if x != nil {
		return x.StuckOrBlocked
	}
	return nil
}

func (x *EngagementAnalyticsResponse) GetMissingOrPartialSignal() []*EngagementStat {
	if x != nil {
		return x.MissingOrPartialSignal
	}
	return nil
}

func (x *EngagementAnalyticsResponse) GetHighMessagesLowTasks() []*EngagementStat {
	if x != nil {
		return x.HighMessagesLowTasks
	}
	return nil
}

type GrowthStat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ItemName       string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	StatValue      float32                `protobuf:"fixed32,2,opt,name=stat_value,json=statValue,proto3" json:"stat_value,omitempty"`
	SecondaryValue float32                `protobuf:"fixed32,3,opt,name=secondary_value,json=secondaryValue,proto3" json:"secondary_value,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GrowthStat) Reset() {
	*x = GrowthStat{}
	mi := &file_proto_performance_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrowthStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrowthStat) ProtoMessage() {}

func (x *GrowthStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrowthStat.ProtoReflect.Descriptor instead.
func (*GrowthStat) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{17}
}

func (x *GrowthStat) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *GrowthStat) GetStatValue() float32 {
	if x != nil {
		return x.StatValue
	}
	return 0
}

func (x *GrowthStat) GetSecondaryValue() float32 {
	if x != nil {
		return x.SecondaryValue
	}
	return 0
}

type GrowthAnalyticsResponse struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	MostXpThisWeek               []*GrowthStat          `protobuf:"bytes,1,rep,name=most_xp_this_week,json=mostXpThisWeek,proto3" json:"most_xp_this_week,omitempty"`
	FrequentAchievements         []*GrowthStat          `protobuf:"bytes,2,rep,name=frequent_achievements,json=frequentAchievements,proto3" json:"frequent_achievements,omitempty"`
	XpVsEvaluations              []*GrowthStat          `protobuf:"bytes,3,rep,name=xp_vs_evaluations,json=xpVsEvaluations,proto3" json:"xp_vs_evaluations,omitempty"`
	StreakVsTasks                []*GrowthStat          `protobuf:"bytes,4,rep,name=streak_vs_tasks,json=streakVsTasks,proto3" json:"streak_vs_tasks,omitempty"`
	FastestXpDomains             []*GrowthStat          `protobuf:"bytes,5,rep,name=fastest_xp_domains,json=fastestXpDomains,proto3" json:"fastest_xp_domains,omitempty"`
	ClosestToLevelUp             []*GrowthStat          `protobuf:"bytes,6,rep,name=closest_to_level_up,json=closestToLevelUp,proto3" json:"closest_to_level_up,omitempty"`
	ActiveGamificationPercentage float32                `protobuf:"fixed32,7,opt,name=active_gamification_percentage,json=activeGamificationPercentage,proto3" json:"active_gamification_percentage,omitempty"`
	StagnatedXpGrowth            []*GrowthStat          `protobuf:"bytes,8,rep,name=stagnated_xp_growth,json=stagnatedXpGrowth,proto3" json:"stagnated_xp_growth,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *GrowthAnalyticsResponse) Reset() {
	*x = GrowthAnalyticsResponse{}
	mi := &file_proto_performance_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrowthAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrowthAnalyticsResponse) ProtoMessage() {}

func (x *GrowthAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrowthAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*GrowthAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{18}
}

func (x *GrowthAnalyticsResponse) GetMostXpThisWeek() []*GrowthStat {
	if x != nil {
		return x.MostXpThisWeek
	}
	return nil
}

func (x *GrowthAnalyticsResponse) GetFrequentAchievements() []*GrowthStat {
	if x != nil {
		return x.FrequentAchievements
	}
	return nil
}

func (x *GrowthAnalyticsResponse) GetXpVsEvaluations() []*GrowthStat {
	if x != nil {
		return x.XpVsEvaluations
	}
	return nil
}

func (x *GrowthAnalyticsResponse) GetStreakVsTasks() []*GrowthStat {
	if x != nil {
		return x.StreakVsTasks
	}
	return nil
}

func (x *GrowthAnalyticsResponse) GetFastestXpDomains() []*GrowthStat {
	if x != nil {
		return x.FastestXpDomains
	}
	return nil
}

func (x *GrowthAnalyticsResponse) GetClosestToLevelUp() []*GrowthStat {
	if x != nil {
		return x.ClosestToLevelUp
	}
	return nil
}

func (x *GrowthAnalyticsResponse) GetActiveGamificationPercentage() float32 {
	if x != nil {
		return x.ActiveGamificationPercentage
	}
	return 0
}

func (x *GrowthAnalyticsResponse) GetStagnatedXpGrowth() []*GrowthStat {
	if x != nil {
		return x.StagnatedXpGrowth
	}
	return nil
}

type CollegeStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CollegeName   string                 `protobuf:"bytes,1,opt,name=college_name,json=collegeName,proto3" json:"college_name,omitempty"`
	StatValue     float32                `protobuf:"fixed32,2,opt,name=stat_value,json=statValue,proto3" json:"stat_value,omitempty"`
	ExtraInfo     string                 `protobuf:"bytes,3,opt,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollegeStat) Reset() {
	*x = CollegeStat{}
	mi := &file_proto_performance_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollegeStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollegeStat) ProtoMessage() {}

func (x *CollegeStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollegeStat.ProtoReflect.Descriptor instead.
func (*CollegeStat) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{19}
}

func (x *CollegeStat) GetCollegeName() string {
	if x != nil {
		return x.CollegeName
	}
	return ""
}

func (x *CollegeStat) GetStatValue() float32 {
	if x != nil {
		return x.StatValue
	}
	return 0
}

func (x *CollegeStat) GetExtraInfo() string {
	if x != nil {
		return x.ExtraInfo
	}
	return ""
}

type CollegeAnalyticsResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	HighestInternCount      []*CollegeStat         `protobuf:"bytes,1,rep,name=highest_intern_count,json=highestInternCount,proto3" json:"highest_intern_count,omitempty"`
	BestPerforming          []*CollegeStat         `protobuf:"bytes,2,rep,name=best_performing,json=bestPerforming,proto3" json:"best_performing,omitempty"`
	HighestCompletionRate   []*CollegeStat         `protobuf:"bytes,3,rep,name=highest_completion_rate,json=highestCompletionRate,proto3" json:"highest_completion_rate,omitempty"`
	HighestDropoutRisk      []*CollegeStat         `protobuf:"bytes,4,rep,name=highest_dropout_risk,json=highestDropoutRisk,proto3" json:"highest_dropout_risk,omitempty"`
	AttendanceTrends        []*CollegeStat         `protobuf:"bytes,5,rep,name=attendance_trends,json=attendanceTrends,proto3" json:"attendance_trends,omitempty"`
	RecommendedForMoreSlots []*CollegeStat         `protobuf:"bytes,6,rep,name=recommended_for_more_slots,json=recommendedForMoreSlots,proto3" json:"recommended_for_more_slots,omitempty"`
	DecliningPerformance    []*CollegeStat         `protobuf:"bytes,7,rep,name=declining_performance,json=decliningPerformance,proto3" json:"declining_performance,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CollegeAnalyticsResponse) Reset() {
	*x = CollegeAnalyticsResponse{}
	mi := &file_proto_performance_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollegeAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollegeAnalyticsResponse) ProtoMessage() {}

func (x *CollegeAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollegeAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*CollegeAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{20}
}

func (x *CollegeAnalyticsResponse) GetHighestInternCount() []*CollegeStat {
	if x != nil {
		return x.HighestInternCount
	}
	return nil
}

func (x *CollegeAnalyticsResponse) GetBestPerforming() []*CollegeStat {
	if x != nil {
		return x.BestPerforming
	}
	return nil
}

func (x *CollegeAnalyticsResponse) GetHighestCompletionRate() []*CollegeStat {
	if x != nil {
		return x.HighestCompletionRate
	}
	return nil
}

func (x *CollegeAnalyticsResponse) GetHighestDropoutRisk() []*CollegeStat {
	if x != nil {
		return x.HighestDropoutRisk
	}
	return nil
}

func (x *CollegeAnalyticsResponse) GetAttendanceTrends() []*CollegeStat {
	if x != nil {
		return x.AttendanceTrends
	}
	return nil
}

func (x *CollegeAnalyticsResponse) GetRecommendedForMoreSlots() []*CollegeStat {
	if x != nil {
		return x.RecommendedForMoreSlots
	}
	return nil
}

func (x *CollegeAnalyticsResponse) GetDecliningPerformance() []*CollegeStat {
	if x != nil {
		return x.DecliningPerformance
	}
	return nil
}

type WorkflowStat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InternName      string                 `protobuf:"bytes,1,opt,name=intern_name,json=internName,proto3" json:"intern_name,omitempty"`
	EscalationLevel float32                `protobuf:"fixed32,2,opt,name=escalation_level,json=escalationLevel,proto3" json:"escalation_level,omitempty"`
	RootCause       string                 `protobuf:"bytes,3,opt,name=root_cause,json=rootCause,proto3" json:"root_cause,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkflowStat) Reset() {
	*x = WorkflowStat{}
	mi := &file_proto_performance_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStat) ProtoMessage() {}

func (x *WorkflowStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStat.ProtoReflect.Descriptor instead.
func (*WorkflowStat) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{21}
}

func (x *WorkflowStat) GetInternName() string {
	if x != nil {
		return x.InternName
	}
	return ""
}

func (x *WorkflowStat) GetEscalationLevel() float32 {
	if x != nil {
		return x.EscalationLevel
	}
	return 0
}

func (x *WorkflowStat) GetRootCause() string {
	if x != nil {
		return x.RootCause
	}
	return ""
}

type WorkflowAnalyticsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EscalatedInterns   []*WorkflowStat        `protobuf:"bytes,1,rep,name=escalated_interns,json=escalatedInterns,proto3" json:"escalated_interns,omitempty"`
	NegativeWeeksTrend []*WorkflowStat        `protobuf:"bytes,2,rep,name=negative_weeks_trend,json=negativeWeeksTrend,proto3" json:"negative_weeks_trend,omitempty"`
	CommonRootCauses   []*WorkflowStat        `protobuf:"bytes,3,rep,name=common_root_causes,json=commonRootCauses,proto3" json:"common_root_causes,omitempty"`
	PastDueDecisions   []*WorkflowStat        `protobuf:"bytes,4,rep,name=past_due_decisions,json=pastDueDecisions,proto3" json:"past_due_decisions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkflowAnalyticsResponse) Reset() {
	*x = WorkflowAnalyticsResponse{}
	mi := &file_proto_performance_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowAnalyticsResponse) ProtoMessage() {}

func (x *WorkflowAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*WorkflowAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{22}
}

func (x *WorkflowAnalyticsResponse) GetEscalatedInterns() []*WorkflowStat {
	if x != nil {
		return x.EscalatedInterns
	}
	return nil
}

func (x *WorkflowAnalyticsResponse) GetNegativeWeeksTrend() []*WorkflowStat {
	if x != nil {
		return x.NegativeWeeksTrend
	}
	return nil
}

func (x *WorkflowAnalyticsResponse) GetCommonRootCauses() []*WorkflowStat {
	if x != nil {
		return x.CommonRootCauses
	}
	return nil
}

func (x *WorkflowAnalyticsResponse) GetPastDueDecisions() []*WorkflowStat {
	if x != nil {
		return x.PastDueDecisions
	}
	return nil
}

type ConversionStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InternName    string                 `protobuf:"bytes,1,opt,name=intern_name,json=internName,proto3" json:"intern_name,omitempty"`
	StatValue     float32                `protobuf:"fixed32,2,opt,name=stat_value,json=statValue,proto3" json:"stat_value,omitempty"`
	ExtraInfo     string                 `protobuf:"bytes,3,opt,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversionStat) Reset() {
	*x = ConversionStat{}
	mi := &file_proto_performance_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversionStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversionStat) ProtoMessage() {}

func (x *ConversionStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversionStat.ProtoReflect.Descriptor instead.
func (*ConversionStat) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{23}
}

func (x *ConversionStat) GetInternName() string {
	if x != nil {
		return x.InternName
	}
	return ""
}

func (x *ConversionStat) GetStatValue() float32 {
	if x != nil {
		return x.StatValue
	}
	return 0
}

func (x *ConversionStat) GetExtraInfo() string {
	if x != nil {
		return x.ExtraInfo
	}
	return ""
}

type ConversionAnalyticsResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	NotStartedApproachingEnd []*ConversionStat      `protobuf:"bytes,1,rep,name=not_started_approaching_end,json=notStartedApproachingEnd,proto3" json:"not_started_approaching_end,omitempty"`
	HighEvalReadyHire        []*ConversionStat      `protobuf:"bytes,2,rep,name=high_eval_ready_hire,json=highEvalReadyHire,proto3" json:"high_eval_ready_hire,omitempty"`
	TopConversionColleges    []*ConversionStat      `protobuf:"bytes,3,rep,name=top_conversion_colleges,json=topConversionColleges,proto3" json:"top_conversion_colleges,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ConversionAnalyticsResponse) Reset() {
	*x = ConversionAnalyticsResponse{}
	mi := &file_proto_performance_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversionAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversionAnalyticsResponse) ProtoMessage() {}

func (x *ConversionAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversionAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*ConversionAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{24}
}

func (x *ConversionAnalyticsResponse) GetNotStartedApproachingEnd() []*ConversionStat {
	if x != nil {
		return x.NotStartedApproachingEnd
	}
	return nil
}

func (x *ConversionAnalyticsResponse) GetHighEvalReadyHire() []*ConversionStat {
	if x != nil {
		return x.HighEvalReadyHire
	}
	return nil
}

func (x *ConversionAnalyticsResponse) GetTopConversionColleges() []*ConversionStat {
	if x != nil {
		return x.TopConversionColleges
	}
	return nil
}

var File_proto_performance_proto protoreflect.FileDescriptor

const file_proto_performance_proto_rawDesc = "" +
	"\n" +
	"\x17proto/performance.proto\x12\x12tarcin.performance\"\a\n" +
	"\x05Empty\"G\n" +
	"\vInternScore\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\"\x8c\x05\n" +
	"\x1aPerformanceMetricsResponse\x12F\n" +
	"\x0etop_performers\x18\x01 \x03(\v2\x1f.tarcin.performance.InternScoreR\rtopPerformers\x12L\n" +
	"\x11lowest_performers\x18\x02 \x03(\v2\x1f.tarcin.performance.InternScoreR\x10lowestPerformers\x128\n" +
	"\x18average_evaluation_score\x18\x03 \x01(\x02R\x16averageEvaluationScore\x12\x81\x01\n" +
	"\x17domain_wise_performance\x18\x04 \x03(\v2I.tarcin.performance.PerformanceMetricsResponse.DomainWisePerformanceEntryR\x15domainWisePerformance\x12\x84\x01\n" +
	"\x18college_wise_performance\x18\x05 \x03(\v2J.tarcin.performance.PerformanceMetricsResponse.CollegeWisePerformanceEntryR\x16collegeWisePerformance\x1aH\n" +
	"\x1aDomainWisePerformanceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1aI\n" +
	"\x1bCollegeWisePerformanceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\x82\x04\n" +
	"\x14InternHealthResponse\x12%\n" +
	"\x0eactive_interns\x18\x01 \x01(\x05R\ractiveInterns\x123\n" +
	"\x15completed_internships\x18\x02 \x01(\x05R\x14completedInternships\x12)\n" +
	"\x10inactive_interns\x18\x03 \x01(\x05R\x0finactiveInterns\x12\\\n" +
	"\ftop_colleges\x18\x04 \x03(\v29.tarcin.performance.InternHealthResponse.TopCollegesEntryR\vtopColleges\x12{\n" +
	"\x17fastest_growing_domains\x18\x05 \x03(\v2C.tarcin.performance.InternHealthResponse.FastestGrowingDomainsEntryR\x15fastestGrowingDomains\x1a>\n" +
	"\x10TopCollegesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aH\n" +
	"\x1aFastestGrowingDomainsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x8d\x01\n" +
	"\x0eInternTaskStat\x12\x1b\n" +
	"\tintern_id\x18\x01 \x01(\tR\binternId\x12\x1f\n" +
	"\vintern_name\x18\x02 \x01(\tR\n" +
	"internName\x12'\n" +
	"\x0fcompletion_rate\x18\x03 \x01(\x02R\x0ecompletionRate\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\";\n" +
	"\rTaskTitleStat\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"Q\n" +
	"\x12DomainApprovalStat\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12#\n" +
	"\rapproval_rate\x18\x02 \x01(\x02R\fapprovalRate\"d\n" +
	"\x0fMentorSpeedStat\x12\x1f\n" +
	"\vmentor_name\x18\x01 \x01(\tR\n" +
	"mentorName\x120\n" +
	"\x14avg_completion_hours\x18\x02 \x01(\x02R\x12avgCompletionHours\"_\n" +
	"\vPendingTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12!\n" +
	"\fdays_pending\x18\x03 \x01(\x05R\vdaysPending\"N\n" +
	"\x13TaskTimeCorrelation\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vavg_minutes\x18\x02 \x01(\x02R\n" +
	"avgMinutes\"\xed\b\n" +
	"\x15TaskAnalyticsResponse\x12Z\n" +
	"\x17highest_completion_rate\x18\x01 \x03(\v2\".tarcin.performance.InternTaskStatR\x15highestCompletionRate\x12J\n" +
	"\x0fmost_late_tasks\x18\x02 \x03(\v2\".tarcin.performance.InternTaskStatR\rmostLateTasks\x12]\n" +
	"\x19frequently_rejected_tasks\x18\x03 \x03(\v2!.tarcin.performance.TaskTitleStatR\x17frequentlyRejectedTasks\x12>\n" +
	"\x1bincomplete_tasks_percentage\x18\x04 \x01(\x02R\x19incompleteTasksPercentage\x12Z\n" +
	"\x15domain_approval_rates\x18\x05 \x03(\v2&.tarcin.performance.DomainApprovalStatR\x13domainApprovalRates\x12Y\n" +
	"\x16fastest_mentor_interns\x18\x06 \x03(\v2#.tarcin.performance.MentorSpeedStatR\x14fastestMentorInterns\x12^\n" +
	"\x19decreased_completion_rate\x18\a \x03(\v2\".tarcin.performance.InternTaskStatR\x17decreasedCompletionRate\x122\n" +
	"\x15top_rejection_reasons\x18\b \x03(\tR\x13topRejectionReasons\x12b\n" +
	"\x1bconsistent_early_submitters\x18\t \x03(\v2\".tarcin.performance.InternTaskStatR\x19consistentEarlySubmitters\x12M\n" +
	"\x12long_pending_tasks\x18\n" +
	" \x03(\v2\x1f.tarcin.performance.PendingTaskR\x10longPendingTasks\x12I\n" +
	"!tasks_without_evidence_percentage\x18\v \x01(\x02R\x1etasksWithoutEvidencePercentage\x12Z\n" +
	"\x18tasks_with_most_blockers\x18\f \x03(\v2!.tarcin.performance.TaskTitleStatR\x15tasksWithMostBlockers\x12h\n" +
	"\x1ctime_vs_approval_correlation\x18\r \x03(\v2'.tarcin.performance.TaskTimeCorrelationR\x19timeVsApprovalCorrelation\"k\n" +
	"\n" +
	"MentorStat\x12\x1f\n" +
	"\vmentor_name\x18\x01 \x01(\tR\n" +
	"mentorName\x12\x1d\n" +
	"\n" +
	"stat_value\x18\x02 \x01(\x02R\tstatValue\x12\x1d\n" +
	"\n" +
	"extra_info\x18\x03 \x01(\tR\textraInfo\"\x85\x01\n" +
	"\x10DomainMentorStat\x12\x1f\n" +
	"\vdomain_name\x18\x01 \x01(\tR\n" +
	"domainName\x12\x1f\n" +
	"\vmentor_name\x18\x02 \x01(\tR\n" +
	"mentorName\x12/\n" +
	"\x13effectiveness_score\x18\x03 \x01(\x02R\x12effectivenessScore\"\xa6\b\n" +
	"\x17MentorAnalyticsResponse\x12P\n" +
	"\x14largest_intern_count\x18\x01 \x03(\v2\x1e.tarcin.performance.MentorStatR\x12largestInternCount\x12T\n" +
	"\x16highest_avg_evaluation\x18\x02 \x03(\v2\x1e.tarcin.performance.MentorStatR\x14highestAvgEvaluation\x12T\n" +
	"\x16lowest_attendance_rate\x18\x03 \x03(\v2\x1e.tarcin.performance.MentorStatR\x14lowestAttendanceRate\x12R\n" +
	"\x15highest_task_approval\x18\x04 \x03(\v2\x1e.tarcin.performance.MentorStatR\x13highestTaskApproval\x12T\n" +
	"\x16highest_retention_rate\x18\x05 \x03(\v2\x1e.tarcin.performance.MentorStatR\x14highestRetentionRate\x12^\n" +
	"\x1bconsistently_miss_deadlines\x18\x06 \x03(\v2\x1e.tarcin.performance.MentorStatR\x19consistentlyMissDeadlines\x12K\n" +
	"\x11balanced_workload\x18\a \x03(\v2\x1e.tarcin.performance.MentorStatR\x10balancedWorkload\x12M\n" +
	"\x12needs_intervention\x18\b \x03(\v2\x1e.tarcin.performance.MentorStatR\x11needsIntervention\x12f\n" +
	"\x1ceffectiveness_across_domains\x18\t \x03(\v2$.tarcin.performance.DomainMentorStatR\x1aeffectivenessAcrossDomains\x12O\n" +
	"\x13lagging_assessments\x18\n" +
	" \x03(\v2\x1e.tarcin.performance.MentorStatR\x12laggingAssessments\x12V\n" +
	"\x17negative_empty_feedback\x18\v \x03(\v2\x1e.tarcin.performance.MentorStatR\x15negativeEmptyFeedback\x12V\n" +
	"\x17disputed_evidence_flags\x18\f \x03(\v2\x1e.tarcin.performance.MentorStatR\x15disputedEvidenceFlags\"\x8c\x01\n" +
	"\x0eEngagementStat\x12\x1b\n" +
	"\tintern_id\x18\x01 \x01(\tR\binternId\x12\x1f\n" +
	"\vintern_name\x18\x02 \x01(\tR\n" +
	"internName\x12\x1d\n" +
	"\n" +
	"stat_value\x18\x03 \x01(\x02R\tstatValue\x12\x1d\n" +
	"\n" +
	"extra_info\x18\x04 \x01(\tR\textraInfo\"l\n" +
	"\x15CollegeEngagementStat\x12!\n" +
	"\fcollege_name\x18\x01 \x01(\tR\vcollegeName\x120\n" +
	"\x14avg_engagement_score\x18\x02 \x01(\x02R\x12avgEngagementScore\"\xdb\a\n" +
	"\x1bEngagementAnalyticsResponse\x12T\n" +
	"\x14no_recent_attendance\x18\x01 \x03(\v2\".tarcin.performance.EngagementStatR\x12noRecentAttendance\x12[\n" +
	"\x17declining_participation\x18\x02 \x03(\v2\".tarcin.performance.EngagementStatR\x16decliningParticipation\x12V\n" +
	"\x15stopped_daily_reports\x18\x03 \x03(\v2\".tarcin.performance.EngagementStatR\x13stoppedDailyReports\x12R\n" +
	"\x13lost_active_streaks\x18\x04 \x03(\v2\".tarcin.performance.EngagementStatR\x11lostActiveStreaks\x12T\n" +
	"\x14most_engaged_interns\x18\x05 \x03(\v2\".tarcin.performance.EngagementStatR\x12mostEngagedInterns\x12J\n" +
	"\x0fat_risk_interns\x18\x06 \x03(\v2\".tarcin.performance.EngagementStatR\ratRiskInterns\x12V\n" +
	"\x15sudden_activity_drops\x18\a \x03(\v2\".tarcin.performance.EngagementStatR\x13suddenActivityDrops\x12[\n" +
	"\x14top_engaged_colleges\x18\b \x03(\v2).tarcin.performance.CollegeEngagementStatR\x12topEngagedColleges\x12L\n" +
	"\x10stuck_or_blocked\x18\t \x03(\v2\".tarcin.performance.EngagementStatR\x0estuckOrBlocked\x12]\n" +
	"\x19missing_or_partial_signal\x18\n" +
	" \x03(\v2\".tarcin.performance.EngagementStatR\x16missingOrPartialSignal\x12Y\n" +
	"\x17high_messages_low_tasks\x18\v \x03(\v2\".tarcin.performance.EngagementStatR\x14highMessagesLowTasks\"q\n" +
	"\n" +
	"GrowthStat\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\x12\x1d\n" +
	"\n" +
	"stat_value\x18\x02 \x01(\x02R\tstatValue\x12'\n" +
	"\x0fsecondary_value\x18\x03 \x01(\x02R\x0esecondaryValue\"\x80\x05\n" +
	"\x17GrowthAnalyticsResponse\x12I\n" +
	"\x11most_xp_this_week\x18\x01 \x03(\v2\x1e.tarcin.performance.GrowthStatR\x0emostXpThisWeek\x12S\n" +
	"\x15frequent_achievements\x18\x02 \x03(\v2\x1e.tarcin.performance.GrowthStatR\x14frequentAchievements\x12J\n" +
	"\x11xp_vs_evaluations\x18\x03 \x03(\v2\x1e.tarcin.performance.GrowthStatR\x0fxpVsEvaluations\x12F\n" +
	"\x0fstreak_vs_tasks\x18\x04 \x03(\v2\x1e.tarcin.performance.GrowthStatR\rstreakVsTasks\x12L\n" +
	"\x12fastest_xp_domains\x18\x05 \x03(\v2\x1e.tarcin.performance.GrowthStatR\x10fastestXpDomains\x12M\n" +
	"\x13closest_to_level_up\x18\x06 \x03(\v2\x1e.tarcin.performance.GrowthStatR\x10closestToLevelUp\x12D\n" +
	"\x1eactive_gamification_percentage\x18\a \x01(\x02R\x1cactiveGamificationPercentage\x12N\n" +
	"\x13stagnated_xp_growth\x18\b \x03(\v2\x1e.tarcin.performance.GrowthStatR\x11stagnatedXpGrowth\"n\n" +
	"\vCollegeStat\x12!\n" +
	"\fcollege_name\x18\x01 \x01(\tR\vcollegeName\x12\x1d\n" +
	"\n" +
	"stat_value\x18\x02 \x01(\x02R\tstatValue\x12\x1d\n" +
	"\n" +
	"extra_info\x18\x03 \x01(\tR\textraInfo\"\xe5\x04\n" +
	"\x18CollegeAnalyticsResponse\x12Q\n" +
	"\x14highest_intern_count\x18\x01 \x03(\v2\x1f.tarcin.performance.CollegeStatR\x12highestInternCount\x12H\n" +
	"\x0fbest_performing\x18\x02 \x03(\v2\x1f.tarcin.performance.CollegeStatR\x0ebestPerforming\x12W\n" +
	"\x17highest_completion_rate\x18\x03 \x03(\v2\x1f.tarcin.performance.CollegeStatR\x15highestCompletionRate\x12Q\n" +
	"\x14highest_dropout_risk\x18\x04 \x03(\v2\x1f.tarcin.performance.CollegeStatR\x12highestDropoutRisk\x12L\n" +
	"\x11attendance_trends\x18\x05 \x03(\v2\x1f.tarcin.performance.CollegeStatR\x10attendanceTrends\x12\\\n" +
	"\x1arecommended_for_more_slots\x18\x06 \x03(\v2\x1f.tarcin.performance.CollegeStatR\x17recommendedForMoreSlots\x12T\n" +
	"\x15declining_performance\x18\a \x03(\v2\x1f.tarcin.performance.CollegeStatR\x14decliningPerformance\"y\n" +
	"\fWorkflowStat\x12\x1f\n" +
	"\vintern_name\x18\x01 \x01(\tR\n" +
	"internName\x12)\n" +
	"\x10escalation_level\x18\x02 \x01(\x02R\x0fescalationLevel\x12\x1d\n" +
	"\n" +
	"root_cause\x18\x03 \x01(\tR\trootCause\"\xde\x02\n" +
	"\x19WorkflowAnalyticsResponse\x12M\n" +
	"\x11escalated_interns\x18\x01 \x03(\v2 .tarcin.performance.WorkflowStatR\x10escalatedInterns\x12R\n" +
	"\x14negative_weeks_trend\x18\x02 \x03(\v2 .tarcin.performance.WorkflowStatR\x12negativeWeeksTrend\x12N\n" +
	"\x12common_root_causes\x18\x03 \x03(\v2 .tarcin.performance.WorkflowStatR\x10commonRootCauses\x12N\n" +
	"\x12past_due_decisions\x18\x04 \x03(\v2 .tarcin.performance.WorkflowStatR\x10pastDueDecisions\"o\n" +
	"\x0eConversionStat\x12\x1f\n" +
	"\vintern_name\x18\x01 \x01(\tR\n" +
	"internName\x12\x1d\n" +
	"\n" +
	"stat_value\x18\x02 \x01(\x02R\tstatValue\x12\x1d\n" +
	"\n" +
	"extra_info\x18\x03 \x01(\tR\textraInfo\"\xb1\x02\n" +
	"\x1bConversionAnalyticsResponse\x12a\n" +
	"\x1bnot_started_approaching_end\x18\x01 \x03(\v2\".tarcin.performance.ConversionStatR\x18notStartedApproachingEnd\x12S\n" +
	"\x14high_eval_ready_hire\x18\x02 \x03(\v2\".tarcin.performance.ConversionStatR\x11highEvalReadyHire\x12Z\n" +
	"\x17top_conversion_colleges\x18\x03 \x03(\v2\".tarcin.performance.ConversionStatR\x15topConversionColleges2\xf4\x06\n" +
	"\x12PerformanceService\x12b\n" +
	"\x15GetPerformanceMetrics\x12\x19.tarcin.performance.Empty\x1a..tarcin.performance.PerformanceMetricsResponse\x12V\n" +
	"\x0fGetInternHealth\x12\x19.tarcin.performance.Empty\x1a(.tarcin.performance.InternHealthResponse\x12X\n" +
	"\x10GetTaskAnalytics\x12\x19.tarcin.performance.Empty\x1a).tarcin.performance.TaskAnalyticsResponse\x12\\\n" +
	"\x12GetMentorAnalytics\x12\x19.tarcin.performance.Empty\x1a+.tarcin.performance.MentorAnalyticsResponse\x12d\n" +
	"\x16GetEngagementAnalytics\x12\x19.tarcin.performance.Empty\x1a/.tarcin.performance.EngagementAnalyticsResponse\x12\\\n" +
	"\x12GetGrowthAnalytics\x12\x19.tarcin.performance.Empty\x1a+.tarcin.performance.GrowthAnalyticsResponse\x12^\n" +
	"\x13GetCollegeAnalytics\x12\x19.tarcin.performance.Empty\x1a,.tarcin.performance.CollegeAnalyticsResponse\x12`\n" +
	"\x14GetWorkflowAnalytics\x12\x19.tarcin.performance.Empty\x1a-.tarcin.performance.WorkflowAnalyticsResponse\x12d\n" +
	"\x16GetConversionAnalytics\x12\x19.tarcin.performance.Empty\x1a/.tarcin.performance.ConversionAnalyticsResponseB\x1aZ\x18backend/internal/grpc/pbb\x06proto3"

var (
	file_proto_performance_proto_rawDescOnce sync.Once
	file_proto_performance_proto_rawDescData []byte
)

func file_proto_performance_proto_rawDescGZIP() []byte {
	file_proto_performance_proto_rawDescOnce.Do(func() {
		file_proto_performance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_performance_proto_rawDesc), len(file_proto_performance_proto_rawDesc)))
	})
	return file_proto_performance_proto_rawDescData
}

var file_proto_performance_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_performance_proto_goTypes = []any{
	(*Empty)(nil),                       // 0: tarcin.performance.Empty
	(*InternScore)(nil),                 // 1: tarcin.performance.InternScore
	(*PerformanceMetricsResponse)(nil),  // 2: tarcin.performance.PerformanceMetricsResponse
	(*InternHealthResponse)(nil),        // 3: tarcin.performance.InternHealthResponse
	(*InternTaskStat)(nil),              // 4: tarcin.performance.InternTaskStat
	(*TaskTitleStat)(nil),               // 5: tarcin.performance.TaskTitleStat
	(*DomainApprovalStat)(nil),          // 6: tarcin.performance.DomainApprovalStat
	(*MentorSpeedStat)(nil),             // 7: tarcin.performance.MentorSpeedStat
	(*PendingTask)(nil),                 // 8: tarcin.performance.PendingTask
	(*TaskTimeCorrelation)(nil),         // 9: tarcin.performance.TaskTimeCorrelation
	(*TaskAnalyticsResponse)(nil),       // 10: tarcin.performance.TaskAnalyticsResponse
	(*MentorStat)(nil),                  // 11: tarcin.performance.MentorStat
	(*DomainMentorStat)(nil),            // 12: tarcin.performance.DomainMentorStat
	(*MentorAnalyticsResponse)(nil),     // 13: tarcin.performance.MentorAnalyticsResponse
	(*EngagementStat)(nil),              // 14: tarcin.performance.EngagementStat
	(*CollegeEngagementStat)(nil),       // 15: tarcin.performance.CollegeEngagementStat
	(*EngagementAnalyticsResponse)(nil), // 16: tarcin.performance.EngagementAnalyticsResponse
	(*GrowthStat)(nil),                  // 17: tarcin.performance.GrowthStat
	(*GrowthAnalyticsResponse)(nil),     // 18: tarcin.performance.GrowthAnalyticsResponse
	(*CollegeStat)(nil),                 // 19: tarcin.performance.CollegeStat
	(*CollegeAnalyticsResponse)(nil),    // 20: tarcin.performance.CollegeAnalyticsResponse
	(*WorkflowStat)(nil),                // 21: tarcin.performance.WorkflowStat
	(*WorkflowAnalyticsResponse)(nil),   // 22: tarcin.performance.WorkflowAnalyticsResponse
	(*ConversionStat)(nil),              // 23: tarcin.performance.ConversionStat
	(*ConversionAnalyticsResponse)(nil), // 24: tarcin.performance.ConversionAnalyticsResponse
	nil,                                 // 25: tarcin.performance.PerformanceMetricsResponse.DomainWisePerformanceEntry
	nil,                                 // 26: tarcin.performance.PerformanceMetricsResponse.CollegeWisePerformanceEntry
	nil,                                 // 27: tarcin.performance.InternHealthResponse.TopCollegesEntry
	nil,                                 // 28: tarcin.performance.InternHealthResponse.FastestGrowingDomainsEntry
}
var file_proto_performance_proto_depIdxs = []int32{
	1,  // 0: tarcin.performance.PerformanceMetricsResponse.top_performers:type_name -> tarcin.performance.InternScore
	1,  // 1: tarcin.performance.PerformanceMetricsResponse.lowest_performers:type_name -> tarcin.performance.InternScore
	25, // 2: tarcin.performance.PerformanceMetricsResponse.domain_wise_performance:type_name -> tarcin.performance.PerformanceMetricsResponse.DomainWisePerformanceEntry
	26, // 3: tarcin.performance.PerformanceMetricsResponse.college_wise_performance:type_name -> tarcin.performance.PerformanceMetricsResponse.CollegeWisePerformanceEntry
	27, // 4: tarcin.performance.InternHealthResponse.top_colleges:type_name -> tarcin.performance.InternHealthResponse.TopCollegesEntry
	28, // 5: tarcin.performance.InternHealthResponse.fastest_growing_domains:type_name -> tarcin.performance.InternHealthResponse.FastestGrowingDomainsEntry
	4,  // 6: tarcin.performance.TaskAnalyticsResponse.highest_completion_rate:type_name -> tarcin.performance.InternTaskStat
	4,  // 7: tarcin.performance.TaskAnalyticsResponse.most_late_tasks:type_name -> tarcin.performance.InternTaskStat
	5,  // 8: tarcin.performance.TaskAnalyticsResponse.frequently_rejected_tasks:type_name -> tarcin.performance.TaskTitleStat
	6,  // 9: tarcin.performance.TaskAnalyticsResponse.domain_approval_rates:type_name -> tarcin.performance.DomainApprovalStat
	7,  // 10: tarcin.performance.TaskAnalyticsResponse.fastest_mentor_interns:type_name -> tarcin.performance.MentorSpeedStat
	4,  // 11: tarcin.performance.TaskAnalyticsResponse.decreased_completion_rate:type_name -> tarcin.performance.InternTaskStat
	4,  // 12: tarcin.performance.TaskAnalyticsResponse.consistent_early_submitters:type_name -> tarcin.performance.InternTaskStat
	8,  // 13: tarcin.performance.TaskAnalyticsResponse.long_pending_tasks:type_name -> tarcin.performance.PendingTask
	5,  // 14: tarcin.performance.TaskAnalyticsResponse.tasks_with_most_blockers:type_name -> tarcin.performance.TaskTitleStat
	9,  // 15: tarcin.performance.TaskAnalyticsResponse.time_vs_approval_correlation:type_name -> tarcin.performance.TaskTimeCorrelation
	11, // 16: tarcin.performance.MentorAnalyticsResponse.largest_intern_count:type_name -> tarcin.performance.MentorStat
	11, // 17: tarcin.performance.MentorAnalyticsResponse.highest_avg_evaluation:type_name -> tarcin.performance.MentorStat
	11, // 18: tarcin.performance.MentorAnalyticsResponse.lowest_attendance_rate:type_name -> tarcin.performance.MentorStat
	11, // 19: tarcin.performance.MentorAnalyticsResponse.highest_task_approval:type_name -> tarcin.performance.MentorStat
	11, // 20: tarcin.performance.MentorAnalyticsResponse.highest_retention_rate:type_name -> tarcin.performance.MentorStat
	11, // 21: tarcin.performance.MentorAnalyticsResponse.consistently_miss_deadlines:type_name -> tarcin.performance.MentorStat
	11, // 22: tarcin.performance.MentorAnalyticsResponse.balanced_workload:type_name -> tarcin.performance.MentorStat
	11, // 23: tarcin.performance.MentorAnalyticsResponse.needs_intervention:type_name -> tarcin.performance.MentorStat
	12, // 24: tarcin.performance.MentorAnalyticsResponse.effectiveness_across_domains:type_name -> tarcin.performance.DomainMentorStat
	11, // 25: tarcin.performance.MentorAnalyticsResponse.lagging_assessments:type_name -> tarcin.performance.MentorStat
	11, // 26: tarcin.performance.MentorAnalyticsResponse.negative_empty_feedback:type_name -> tarcin.performance.MentorStat
	11, // 27: tarcin.performance.MentorAnalyticsResponse.disputed_evidence_flags:type_name -> tarcin.performance.MentorStat
	14, // 28: tarcin.performance.EngagementAnalyticsResponse.no_recent_attendance:type_name -> tarcin.performance.EngagementStat
	14, // 29: tarcin.performance.EngagementAnalyticsResponse.declining_participation:type_name -> tarcin.performance.EngagementStat
	14, // 30: tarcin.performance.EngagementAnalyticsResponse.stopped_daily_reports:type_name -> tarcin.performance.EngagementStat
	14, // 31: tarcin.performance.EngagementAnalyticsResponse.lost_active_streaks:type_name -> tarcin.performance.EngagementStat
	14, // 32: tarcin.performance.EngagementAnalyticsResponse.most_engaged_interns:type_name -> tarcin.performance.EngagementStat
	14, // 33: tarcin.performance.EngagementAnalyticsResponse.at_risk_interns:type_name -> tarcin.performance.EngagementStat
	14, // 34: tarcin.performance.EngagementAnalyticsResponse.sudden_activity_drops:type_name -> tarcin.performance.EngagementStat
	15, // 35: tarcin.performance.EngagementAnalyticsResponse.top_engaged_colleges:type_name -> tarcin.performance.CollegeEngagementStat
	14, // 36: tarcin.performance.EngagementAnalyticsResponse.stuck_or_blocked:type_name -> tarcin.performance.EngagementStat
	14, // 37: tarcin.performance.EngagementAnalyticsResponse.missing_or_partial_signal:type_name -> tarcin.performance.EngagementStat
	14, // 38: tarcin.performance.EngagementAnalyticsResponse.high_messages_low_tasks:type_name -> tarcin.performance.EngagementStat
	17, // 39: tarcin.performance.GrowthAnalyticsResponse.most_xp_this_week:type_name -> tarcin.performance.GrowthStat
	17, // 40: tarcin.performance.GrowthAnalyticsResponse.frequent_achievements:type_name -> tarcin.performance.GrowthStat
	17, // 41: tarcin.performance.GrowthAnalyticsResponse.xp_vs_evaluations:type_name -> tarcin.performance.GrowthStat
	17, // 42: tarcin.performance.GrowthAnalyticsResponse.streak_vs_tasks:type_name -> tarcin.performance.GrowthStat
	17, // 43: tarcin.performance.GrowthAnalyticsResponse.fastest_xp_domains:type_name -> tarcin.performance.GrowthStat
	17, // 44: tarcin.performance.GrowthAnalyticsResponse.closest_to_level_up:type_name -> tarcin.performance.GrowthStat
	17, // 45: tarcin.performance.GrowthAnalyticsResponse.stagnated_xp_growth:type_name -> tarcin.performance.GrowthStat
	19, // 46: tarcin.performance.CollegeAnalyticsResponse.highest_intern_count:type_name -> tarcin.performance.CollegeStat
	19, // 47: tarcin.performance.CollegeAnalyticsResponse.best_performing:type_name -> tarcin.performance.CollegeStat
	19, // 48: tarcin.performance.CollegeAnalyticsResponse.highest_completion_rate:type_name -> tarcin.performance.CollegeStat
	19, // 49: tarcin.performance.CollegeAnalyticsResponse.highest_dropout_risk:type_name -> tarcin.performance.CollegeStat
	19, // 50: tarcin.performance.CollegeAnalyticsResponse.attendance_trends:type_name -> tarcin.performance.CollegeStat
	19, // 51: tarcin.performance.CollegeAnalyticsResponse.recommended_for_more_slots:type_name -> tarcin.performance.CollegeStat
	19, // 52: tarcin.performance.CollegeAnalyticsResponse.declining_performance:type_name -> tarcin.performance.CollegeStat
	21, // 53: tarcin.performance.WorkflowAnalyticsResponse.escalated_interns:type_name -> tarcin.performance.WorkflowStat
	21, // 54: tarcin.performance.WorkflowAnalyticsResponse.negative_weeks_trend:type_name -> tarcin.performance.WorkflowStat
	21, // 55: tarcin.performance.WorkflowAnalyticsResponse.common_root_causes:type_name -> tarcin.performance.WorkflowStat
	21, // 56: tarcin.performance.WorkflowAnalyticsResponse.past_due_decisions:type_name -> tarcin.performance.WorkflowStat
	23, // 57: tarcin.performance.ConversionAnalyticsResponse.not_started_approaching_end:type_name -> tarcin.performance.ConversionStat
	23, // 58: tarcin.performance.ConversionAnalyticsResponse.high_eval_ready_hire:type_name -> tarcin.performance.ConversionStat
	23, // 59: tarcin.performance.ConversionAnalyticsResponse.top_conversion_colleges:type_name -> tarcin.performance.ConversionStat
	0,  // 60: tarcin.performance.PerformanceService.GetPerformanceMetrics:input_type -> tarcin.performance.Empty
	0,  // 61: tarcin.performance.PerformanceService.GetInternHealth:input_type -> tarcin.performance.Empty
	0,  // 62: tarcin.performance.PerformanceService.GetTaskAnalytics:input_type -> tarcin.performance.Empty
	0,  // 63: tarcin.performance.PerformanceService.GetMentorAnalytics:input_type -> tarcin.performance.Empty
	0,  // 64: tarcin.performance.PerformanceService.GetEngagementAnalytics:input_type -> tarcin.performance.Empty
	0,  // 65: tarcin.performance.PerformanceService.GetGrowthAnalytics:input_type -> tarcin.performance.Empty
	0,  // 66: tarcin.performance.PerformanceService.GetCollegeAnalytics:input_type -> tarcin.performance.Empty
	0,  // 67: tarcin.performance.PerformanceService.GetWorkflowAnalytics:input_type -> tarcin.performance.Empty
	0,  // 68: tarcin.performance.PerformanceService.GetConversionAnalytics:input_type -> tarcin.performance.Empty
	2,  // 69: tarcin.performance.PerformanceService.GetPerformanceMetrics:output_type -> tarcin.performance.PerformanceMetricsResponse
	3,  // 70: tarcin.performance.PerformanceService.GetInternHealth:output_type -> tarcin.performance.InternHealthResponse
	10, // 71: tarcin.performance.PerformanceService.GetTaskAnalytics:output_type -> tarcin.performance.TaskAnalyticsResponse
	13, // 72: tarcin.performance.PerformanceService.GetMentorAnalytics:output_type -> tarcin.performance.MentorAnalyticsResponse
	16, // 73: tarcin.performance.PerformanceService.GetEngagementAnalytics:output_type -> tarcin.performance.EngagementAnalyticsResponse
	18, // 74: tarcin.performance.PerformanceService.GetGrowthAnalytics:output_type -> tarcin.performance.GrowthAnalyticsResponse
	20, // 75: tarcin.performance.PerformanceService.GetCollegeAnalytics:output_type -> tarcin.performance.CollegeAnalyticsResponse
	22, // 76: tarcin.performance.PerformanceService.GetWorkflowAnalytics:output_type -> tarcin.performance.WorkflowAnalyticsResponse
	24, // 77: tarcin.performance.PerformanceService.GetConversionAnalytics:output_type -> tarcin.performance.ConversionAnalyticsResponse
	69, // [69:78] is the sub-list for method output_type
	60, // [60:69] is the sub-list for method input_type
	60, // [60:60] is the sub-list for extension type_name
	60, // [60:60] is the sub-list for extension extendee
	0,  // [0:60] is the sub-list for field type_name
}

func init() { file_proto_performance_proto_init() }
func file_proto_performance_proto_init() {
	if File_proto_performance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_performance_proto_rawDesc), len(file_proto_performance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_performance_proto_goTypes,
		DependencyIndexes: file_proto_performance_proto_depIdxs,
		MessageInfos:      file_proto_performance_proto_msgTypes,
	}.Build()
	File_proto_performance_proto = out.File
	file_proto_performance_proto_goTypes = nil
	file_proto_performance_proto_depIdxs = nil
}
