// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/performance.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_performance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{0}
}

type SQLQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLQueryRequest) Reset() {
	*x = SQLQueryRequest{}
	mi := &file_proto_performance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLQueryRequest) ProtoMessage() {}

func (x *SQLQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLQueryRequest.ProtoReflect.Descriptor instead.
func (*SQLQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{1}
}

func (x *SQLQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SQLQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonResult    string                 `protobuf:"bytes,1,opt,name=json_result,json=jsonResult,proto3" json:"json_result,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLQueryResponse) Reset() {
	*x = SQLQueryResponse{}
	mi := &file_proto_performance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLQueryResponse) ProtoMessage() {}

func (x *SQLQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_performance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLQueryResponse.ProtoReflect.Descriptor instead.
func (*SQLQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_performance_proto_rawDescGZIP(), []int{2}
}

func (x *SQLQueryResponse) GetJsonResult() string {
	if x != nil {
		return x.JsonResult
	}
	return ""
}

func (x *SQLQueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_performance_proto protoreflect.FileDescriptor

const file_proto_performance_proto_rawDesc = "" +
	"\n" +
	"\x17proto/performance.proto\x12\x12tarcin.performance\"\a\n" +
	"\x05Empty\"'\n" +
	"\x0fSQLQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"I\n" +
	"\x10SQLQueryResponse\x12\x1f\n" +
	"\vjson_result\x18\x01 \x01(\tR\n" +
	"jsonResult\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2r\n" +
	"\x12PerformanceService\x12\\\n" +
	"\x0fExecuteSQLQuery\x12#.tarcin.performance.SQLQueryRequest\x1a$.tarcin.performance.SQLQueryResponseB\x1aZ\x18backend/internal/grpc/pbb\x06proto3"

var (
	file_proto_performance_proto_rawDescOnce sync.Once
	file_proto_performance_proto_rawDescData []byte
)

func file_proto_performance_proto_rawDescGZIP() []byte {
	file_proto_performance_proto_rawDescOnce.Do(func() {
		file_proto_performance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_performance_proto_rawDesc), len(file_proto_performance_proto_rawDesc)))
	})
	return file_proto_performance_proto_rawDescData
}

var file_proto_performance_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_performance_proto_goTypes = []any{
	(*Empty)(nil),            // 0: tarcin.performance.Empty
	(*SQLQueryRequest)(nil),  // 1: tarcin.performance.SQLQueryRequest
	(*SQLQueryResponse)(nil), // 2: tarcin.performance.SQLQueryResponse
}
var file_proto_performance_proto_depIdxs = []int32{
	1, // 0: tarcin.performance.PerformanceService.ExecuteSQLQuery:input_type -> tarcin.performance.SQLQueryRequest
	2, // 1: tarcin.performance.PerformanceService.ExecuteSQLQuery:output_type -> tarcin.performance.SQLQueryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_performance_proto_init() }
func file_proto_performance_proto_init() {
	if File_proto_performance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_performance_proto_rawDesc), len(file_proto_performance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_performance_proto_goTypes,
		DependencyIndexes: file_proto_performance_proto_depIdxs,
		MessageInfos:      file_proto_performance_proto_msgTypes,
	}.Build()
	File_proto_performance_proto = out.File
	file_proto_performance_proto_goTypes = nil
	file_proto_performance_proto_depIdxs = nil
}
