# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: performance.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'performance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11performance.proto\x12\x12tarcin.performance\"\x07\n\x05\x45mpty\"\"\n\x0bUserRequest\x12\x13\n\x0b\x65mail_or_id\x18\x01 \x01(\t\"2\n\x0cUserResponse\x12\x13\n\x0bjson_result\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t2m\n\x12PerformanceService\x12W\n\x12GetUserInformation\x12\x1f.tarcin.performance.UserRequest\x1a .tarcin.performance.UserResponseB\x1aZ\x18\x62\x61\x63kend/internal/grpc/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'performance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030backend/internal/grpc/pb'
  _globals['_EMPTY']._serialized_start=41
  _globals['_EMPTY']._serialized_end=48
  _globals['_USERREQUEST']._serialized_start=50
  _globals['_USERREQUEST']._serialized_end=84
  _globals['_USERRESPONSE']._serialized_start=86
  _globals['_USERRESPONSE']._serialized_end=136
  _globals['_PERFORMANCESERVICE']._serialized_start=138
  _globals['_PERFORMANCESERVICE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
